name: stovemason
favicon: null
layout_spectrum: 0.08417639043182135
typography_spectrum: 0.19381119566969573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36522859847173095
  lightness: 0.7029566876590252
  saturation: 0.9590628996957093
  rhythmicContrast: 0.11159072583541274
purpose: []
